### PR TITLE
Remove unneeded dependency cligen

### LINKED ISSUE #42: Broken on devel
```nim
$ nimble install inim
Downloading https://github.com/AndreiRegiani/INim using git
  Verifying dependencies for inim@0.4.1
      Info: Dependency on cligen@>= 0.9.15 already satisfied
  Verifying dependencies for cligen@0.9.15
 Installing inim@0.4.1
   Building inim/inim using c backend
    Prompt: Build failed for 'inim@0.4.1', would you like to try installing 'inim@#head' (latest unstable)? [y/N]
    Answer: y
Downloading https://github.com/AndreiRegiani/INim using git
  Verifying dependencies for inim@#head
      Info: Dependency on cligen@>= 0.9.15 already satisfied
  Verifying dependencies for cligen@0.9.15
 Installing inim@#head
   Building inim/inim using c backend
       Tip: 13 messages have been suppressed, use --verbose to show them.
     Error: nimble.nim(1106)         nimble
        ... nimble.nim(1044)         doAction
        ... nimble.nim(497)          install
        ... nimble.nim(483)          install
        ... nimble.nim(359)          installFromDir
        ... nimble.nim(253)          buildFromDir
        ... nimble.nim(245)          buildFromDir
        ... Build failed for package: inim
        ... Details:
        ... nimble.nim(1106)         nimble
        ... nimble.nim(1044)         doAction
        ... nimble.nim(497)          install
        ... nimble.nim(483)          install
        ... nimble.nim(359)          installFromDir
        ... nimble.nim(253)          buildFromDir
        ... nimble.nim(237)          buildFromDir
        ... tools.nim(37)            doCmd
        ... Execution failed with exit code 1
        ... Command: "/home/juan/.nimble/bin/nim" c --noBabelPath -d:release --path:"/home/juan/.nimble/pkgs/cligen-0.9.15"  -o:"/tmp/nimble_7403/githubcom_AndreiRegianiINim_#head/inim" "/tmp/nimble_7403/githubcom_AndreiRegianiINim_#head/src/inim.nim"
        ... Output: Hint: used config file '/home/juan/.choosenim/toolchains/nim-#devel/config/nim.cfg' [Conf]
        ... Hint: system [Processing]
        ... Hint: inim [Processing]
        ... Hint: os [Processing]
        ... Hint: strutils [Processing]
        ... Hint: parseutils [Processing]
        ... Hint: math [Processing]
        ... Hint: bitops [Processing]
        ... Hint: algorithm [Processing]
        ... Hint: unicode [Processing]
        ... Hint: times [Processing]
        ... Hint: options [Processing]
        ... Hint: typetraits [Processing]
        ... Hint: strformat [Processing]
        ... Hint: macros [Processing]
        ... Hint: posix [Processing]
        ... Hint: ospaths [Processing]
        ... Hint: osproc [Processing]
        ... Hint: strtabs [Processing]
        ... Hint: hashes [Processing]
        ... Hint: streams [Processing]
        ... Hint: cpuinfo [Processing]
        ... Hint: linux [Processing]
        ... Hint: rdstdin [Processing]
        ... Hint: linenoise [Processing]
        ... Hint: termios [Processing]
        ... Hint: terminal [Processing]
        ... Hint: colors [Processing]
        ... Hint: tables [Processing]
        ... inim.nim(79, 16) Error: type mismatch: got <nil> but expected 'string'

$ choosenim --version
choosenim v0.3.2 (2018-02-28 14:12:37) [linux/amd64]

$ choosenim show
   Channel: devel
   Version: #devel
      Path: /home/juan/.choosenim/toolchains/nim-#devel

$ uname -a
Linux z 4.18.7-arch1-1-ARCH #1 SMP PREEMPT Sun Sep 9 11:27:58 UTC 2018 x86_64 GNU/Linux

$ nim --version
Nim Compiler Version 0.18.1 [Linux: amd64]
Compiled at 2018-09-14
Copyright (c) 2006-2018 by Andreas Rumpf

active boot switches: -d:release
```

### LINKED ISSUE #43: Can't install inim.
C:\Users\User>nimble install inim
Downloading https://github.com/AndreiRegiani/INim using git
  Verifying dependencies for inim@0.4.1
      Info: Dependency on cligen@>= 0.9.15 already satisfied
  Verifying dependencies for cligen@0.9.16
 Installing inim@0.4.1
   Building inim/inim.exe using c backend
    Prompt: Build failed for 'inim@0.4.1', would you like to try installing 'inim@#head' (latest unstable)? [y/N]
    Answer: y
Downloading https://github.com/AndreiRegiani/INim using git
  Verifying dependencies for inim@#head
      Info: Dependency on cligen@>= 0.9.15 already satisfied
  Verifying dependencies for cligen@0.9.16
 Installing inim@#head
   Building inim/inim.exe using c backend
       Tip: 13 messages have been suppressed, use --verbose to show them.
     Error: Build failed for package: inim
        ... Details:
        ... Execution failed with exit code 1
        ... Command: "C:\Users\User\Downloads\nim-0.19.0\bin\nim.exe" c --noBabelPath -d:release --path:"C:\Users\User\.nimble\pkgs\cligen-0.9.16"  -o:"C:\Users\User\AppData\Local\Temp\nimble_3652\githubcom_AndreiRegianiINim_#head\inim.exe" "C:\Users\User\AppData\Local\Temp\nimble_3652\githubcom_AndreiRegianiINim_#head\src\inim.nim"
        ... Output: Hint: used config file 'C:\Users\User\Downloads\nim-0.19.0\config\nim.cfg' [Conf]
        ... Hint: system [Processing]
        ... Hint: inim [Processing]
        ... Hint: os [Processing]
        ... Hint: strutils [Processing]
        ... Hint: parseutils [Processing]
        ... Hint: math [Processing]
        ... Hint: bitops [Processing]
        ... Hint: algorithm [Processing]
        ... Hint: unicode [Processing]
        ... Hint: times [Processing]
        ... Hint: options [Processing]
        ... Hint: typetraits [Processing]
        ... Hint: strformat [Processing]
        ... Hint: macros [Processing]
        ... Hint: winlean [Processing]
        ... Hint: dynlib [Processing]
        ... Hint: ospaths [Processing]
        ... Hint: osproc [Processing]
        ... Hint: strtabs [Processing]
        ... Hint: hashes [Processing]
        ... Hint: streams [Processing]
        ... Hint: cpuinfo [Processing]
        ... Hint: rdstdin [Processing]
        ... Hint: terminal [Processing]
        ... Hint: colors [Processing]
        ... Hint: tables [Processing]
        ... inim.nim(79, 16) Error: type mismatch: got <nil> but expected 'string'

### PR DESCRIPTION
**Pull request by renannprado**
This closes #42 and closes #43

### CODE REVIEW

**Comment by Yardanico** [comment]
Well, this also removes the help :D

**Comment by juancarlospaco** [comment]
Awesome!. :thinking:

**Comment by AndreiRegiani** [comment]
@renannprado you should also remove `requires "cligen >= 0.9.15"` from `inim.nimble`

I'm ok to remove this dependency, this is something quite simple to implement using only stdlib, I can do it later, anyway I'd prefer INim to not use any third-party dependencies so one day it come as one of the core tools? Maybe one day, right now INim is a huge hack but works better than the "'secret REPL".

**Comment by kaushalmodi** [comment]
Is there any reason to remove the awesome cligen module now? :)

I think cligen use serves as a "best practice" on writing CLI apps in Nim in my opinion.

**Pull request closed without merging**
