### PR TITLE
If merged, this commit introduced printing without using "echo"

### PR DESCRIPTION
**Pull request by Tangdongle**
Checks for discard string and prepend an echo to it

### CODE REVIEW

**Comment by 0atman** [comment]
@AndreiRegiani could this be merged? It's a great feature!

**Comment by 0atman** [comment]
@AndreiRegiani has kindly given me permission to review PRs.

@Tangdongle Thanks so much for this PR, it does indeed work once, but errors the second time, and HANGS the third time!

```
 λ ./inim
👑 INim 0.4.1
Nim Compiler Version 1.0.6 [Linux: amd64] at /home/oatman/.nimble/bin/nim
nim> 1
1
nim> 1
Error: expression '1' is of type 'int literal(1)' and has to be discarded; start of expression here: /tmp/inim_1586104151.nim(1, 1)
nim> 1
^C⏎     # froze here

 λ ./inim
👑 INim 0.4.1
Nim Compiler Version 1.0.6 [Linux: amd64] at /home/oatman/.nimble/bin/nim
nim> "test"
test
nim> "test"
Error: expression '"test"' is of type 'string' and has to be discarded; start of expression here: /tmp/inim_1586104158.nim(1, 1)
nim> "test"
^C⏎    #froze here again
```

But it seems to hang after a second invocation! Can you see what is wrong?

**Comment by Tangdongle** [comment]
Oh man, what was I thinking? I'll see what's going on, I think I just need to remove the printed line from the history buffer

**Comment by Tangdongle** [comment]
Hey, I've made changes to fix up the prior issues. Should work a lot better (ie, it should actually work) now

**Comment by 0atman** [comment]
Thanks so much @Tangdongle! If you hit me with any other easily-testable stuff like this, I'll merge'em!

**Comment by 0atman** [comment]
This is now in release 0.4.2 :ok_hand:

**Comment by 0atman** [comment]
fixes #49

**Comment by 0atman** [comment]
fixes #62

**Pull request merged**
